version: "3.9"

services:
  userpostgresdb:
    image: postgres:16.2-alpine3.19
    container_name: 'userpostgresdb'
    restart: always
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=dangerous
    ports:
      - 5432:5432
    networks:
        - backend_network

  chatpostgresdb:
    image: postgres:16.2-alpine3.19
    container_name: 'chatpostgresdb'
    restart: always
    environment:
      - POSTGRES_DB=chatdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=dangerous
    ports:
      - 5434:5432
    networks:
        - backend_network

  redis:
    container_name: redis_cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
        - backend_network
      
  chat-services:
    image: chat-services:latest
    container_name: 'chat-services'
    build:
      context: ./chat-services  # path to the chat-services directory
    ports:
      - 8082:8080
    networks:
        - backend_network
    depends_on:
      - chatpostgresdb

  user-services:
    image: user-services:latest
    container_name: 'user-services'
    restart: always
    build:
      context: ./user-services  # path to the user-services directory
    ports:
      - 8080:8080
    networks:
        - backend_network
    depends_on:
      - userpostgresdb

networks:
  backend_network:
    driver: bridge
  
